development:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>

test:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
        
production:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>


      
